# Generated by Django 2.2.1 on 2021-01-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210121_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contactno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
